version: '2'
services:
  jhipsteruaaserver-app:
    image: jhipsteruaaserver
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATA_CASSANDRA_CONTACTPOINTS=jhipsteruaaserver-cassandra
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
      - JAVA_OPTS=-Djgroups.tcp.address=NON_LOOPBACK -Djava.net.preferIPv4Stack=true
  jhipsteruaaserver-cassandra:
    extends:
      file: cassandra-cluster.yml
      service: jhipsteruaaserver-cassandra
  jhipsteruaaserver-cassandra-node:
    image: cassandra:3.11.5
    environment:
      - CASSANDRA_SEEDS=jhipsteruaaserver-cassandra
  jhipsteruaaserver-cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: jhipsteruaaserver-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  consul:
    extends:
      file: consul.yml
      service: consul

  consul-config-loader:
    extends:
      file: consul.yml
      service: consul-config-loader
